service: sandworm-collect
frameworkVersion: '3'

plugins:
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs14.x
  httpApi:
    cors: true
  iam:
    role:
      name: lambda-sandworm-collector-role

functions:
  ingest:
    handler: handler.ingest
    events:
      - httpApi:
          path: /
          method: post

custom:
  customDomain:
    domainName: collect.sandworm.dev
    stage: prod
    certificateName: 'sandworm.dev'
    createRoute53Record: false
    createRoute53IPv6Record: false
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: http
    autoDomain: true
